export interface Province {
    id: string;
    name: string;
}

export const PROVINCES: Province[] = [
    { id: "ANGIANG", name: "An Giang" },
    { id: "BARIAVUNGTAU", name: "Bà Rịa - Vũng Tàu" },
    { id: "BACGIANG", name: "Bắc Giang" },
    { id: "BACKAN", name: "Bắc Kạn" },
    { id: "BACLIEU", name: "Bạc Liêu" },
    { id: "BACNINH", name: "Bắc Ninh" },
    { id: "BENTRE", name: "Bến Tre" },
    { id: "BINHDINH", name: "Bình Định" },
    { id: "BINHDUONG", name: "Bình Dương" },
    { id: "BINHPHUOC", name: "Bình Phước" },
    { id: "BINHTHUAN", name: "Bình Thuận" },
    { id: "CAMAU", name: "Cà Mau" },
    { id: "CANTHO", name: "Cần Thơ" },
    { id: "CAOBANG", name: "Cao Bằng" },
    { id: "DANANG", name: "Đà Nẵng" },
    { id: "DAKLAK", name: "Đắk Lắk" },
    { id: "DAKNONG", name: "Đắk Nông" },
    { id: "DIENBIEN", name: "Điện Biên" },
    { id: "DONGNAI", name: "Đồng Nai" },
    { id: "DONGTHAP", name: "Đồng Tháp" },
    { id: "GIALAI", name: "Gia Lai" },
    { id: "HAGIANG", name: "Hà Giang" },
    { id: "HANAM", name: "Hà Nam" },
    { id: "HANOI", name: "Hà Nội" },
    { id: "HATINH", name: "Hà Tĩnh" },
    { id: "HAIDUONG", name: "Hải Dương" },
    { id: "HAIPHONG", name: "Hải Phòng" },
    { id: "HAUGIANG", name: "Hậu Giang" },
    { id: "HOABINH", name: "Hòa Bình" },
    { id: "HUNGYEN", name: "Hưng Yên" },
    { id: "KHANHHOA", name: "Khánh Hòa" },
    { id: "KIENGIANG", name: "Kiên Giang" },
    { id: "KONTUM", name: "Kon Tum" },
    { id: "LAICHAU", name: "Lai Châu" },
    { id: "LAMDONG", name: "Lâm Đồng" },
    { id: "LANGSON", name: "Lạng Sơn" },
    { id: "LAOCAI", name: "Lào Cai" },
    { id: "LONGAN", name: "Long An" },
    { id: "NAMDINH", name: "Nam Định" },
    { id: "NGHEAN", name: "Nghệ An" },
    { id: "NINHBINH", name: "Ninh Bình" },
    { id: "NINHTHUAN", name: "Ninh Thuận" },
    { id: "PHUTHO", name: "Phú Thọ" },
    { id: "PHUYEN", name: "Phú Yên" },
    { id: "QUANGBINH", name: "Quảng Bình" },
    { id: "QUANGNAM", name: "Quảng Nam" },
    { id: "QUANGNGAI", name: "Quảng Ngãi" },
    { id: "QUANGNINH", name: "Quảng Ninh" },
    { id: "QUANGTRI", name: "Quảng Trị" },
    { id: "SOCTRANG", name: "Sóc Trăng" },
    { id: "SONLA", name: "Sơn La" },
    { id: "TAYNINH", name: "Tây Ninh" },
    { id: "THAIBINH", name: "Thái Bình" },
    { id: "THAINGUYEN", name: "Thái Nguyên" },
    { id: "THANHHOA", name: "Thanh Hóa" },
    { id: "THUATHIENHUE", name: "Thừa Thiên Huế" },
    { id: "TIENGIANG", name: "Tiền Giang" },
    { id: "HOCHIMINH", name: "TP Hồ Chí Minh" },
    { id: "TRAVINH", name: "Trà Vinh" },
    { id: "TUYENQUANG", name: "Tuyên Quang" },
    { id: "VINHLONG", name: "Vĩnh Long" },
    { id: "VINHPHUC", name: "Vĩnh Phúc" },
    { id: "YENBAI", name: "Yên Bái" },
    { id: "BENXEMYDINH", name: "Bến xe Mỹ Đình" },
    { id: "BENXEGIAPBAT", name: "Bến xe Giáp Bát" },
    { id: "BENXENUOCNGAM", name: "Bến xe Nước Ngầm" }
]; 